version: "3.1"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  lemmatizer:
    build:
      context: ./functions/lemmatizer/en
      dockerfile: Dockerfile
    ports:
      - "4001:8080"
