steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - "--build-arg"
      - "MONGODB_URL=$$MONGODB_URL"
      - "--build-arg"
      - "NEXTAUTH_SECRET=$$NEXTAUTH_SECRET"
      - "--build-arg"
      - "GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID"
      - "--build-arg"
      - "GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET"
      - "--build-arg"
      - "ENGLISH_LEMMATIZER_URL=$$ENGLISH_LEMMATIZER_URL"
      - "--build-arg"
      - "OPENAI_API_KEY=$$OPENAI_API_KEY"
      - client
      - "-f"
      - client/Dockerfile
    id: Build
    secretEnv:
      [
        "MONGODB_URL",
        "NEXTAUTH_SECRET",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "ENGLISH_LEMMATIZER_URL",
        "OPENAI_API_KEY",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _TRIGGER_ID: db896fbf-1536-44ad-aa6f-d74d5c28cc0d
  _SERVICE_NAME: client
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - client
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MONGODB_URL/versions/latest
      env: "MONGODB_URL"
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_SECRET/versions/latest
      env: "NEXTAUTH_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: "GOOGLE_CLIENT_ID"
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: "GOOGLE_CLIENT_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/ENGLISH_LEMMATIZER_URL/versions/latest
      env: "ENGLISH_LEMMATIZER_URL"
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: "OPENAI_API_KEY"
